### ISSUE TITLE
catkin build error - bish_segementation_dataset_creation

### ISSUE THREAD

**Issue by ArunimJoarder** [RMonica/bish_segmentation#2]
I am having an issue in building the `bish_segmentation_dataset_creation` package, the build fails with an internal compiler error. The error message is attached below.
```
___________________________________________________________________________________________________________________________________________________________________________________
Errors     << bish_segmentation_dataset_creation:make /catkin_ws/logs/bish_segmentation_dataset_creation/build.make.003.log                                                        
/catkin_ws/src/bish_segmentation/bish_segmentation_dataset_creation/src/main.cpp: In lambda function:
/catkin_ws/src/bish_segmentation/bish_segmentation_dataset_creation/src/main.cpp:174:98: internal compiler error: in expand_expr_real_1, at expr.c:9929
         std::min_element(c.begin(), c.end(), [&dist_matrix, i](const int a, const int b) -> bool {
                                                                                                  ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/bish_segmentation_dataset_creation.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/bish_segmentation_dataset_creation.dir/all] Error 2
make: *** [all] Error 2
cd /catkin_ws/build/bish_segmentation_dataset_creation; catkin build --get-env bish_segmentation_dataset_creation | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...................................................................................................................................................................................

```
The build compiles successfully for the `bish_segementation` package, but it fails specifically for 'bish_segmentation_dataset_creation`. Could you give some suggestions?

I am using a docker image from `osrf/ros:melodic-desktop-full` with `libglew-dev`, `python-opencv`, `libeigen3-dev`, `libpcl-dev` installed. I have also cloned the `init_fake_opengl_context` repository to my system.

**Comment by RMonica** [comment]
This is a compiler (GCC) bug, and it should be reported to the compiler developers, not me. Please read the README file reported in the error. Before doing that, you should also upgrade GCC to the latest version, which may be difficult to do since you are using Docker.
Alternatively, you may try a different Docker image, which may not have this bug.

Sorry, but I can't help you with this.
